//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace DocsisLibrary
{
    /// <remarks/>
    [GeneratedCode("xsd", "4.0.30319.1")]
    [Serializable]
    [DebuggerStepThrough]
    [DesignerCategory("code")]
    [XmlType(AnonymousType = true)]
    [XmlRoot("Root", Namespace = "", IsNullable = false)]
    public class SymbolTable
    {
        private List<Param> paramField = new List<Param>();

        public Param this[string value]
        {
            get
            {
                foreach (var parmElement in paramField)
                {
                    if (parmElement.Name.Trim('\r').Trim('\n').Equals(value, StringComparison.InvariantCultureIgnoreCase))
                        return parmElement;
                }
                return null;
            }
        }
        /// <remarks/>
        [XmlElement("Param")]
        public List<Param> Param
        {
            get
            {
                return paramField;
            }
            set
            {
                paramField = value;
            }
        }
    }

    public class Param
    {
        private int _tlv;
        private string _name;
        private string _encode;
        private string _decode;
        private string _minValue;
        private string _maxValue;
        private SymbolTable _group;

        public int TLV
        {
            get
            {
                return _tlv;
            }
            set
            {
                _tlv = value;
            }
        }

        public string Name
        {
            get
            {
                return _name.Trim('\r').Trim('\n').Trim();
            }
            set
            {
                _name = value.Trim('\r').Trim('\n').Trim();
            }
        }

        public string Encode
        {
            get
            {
                return _encode;
            }
            set
            {
                _encode = value;
            }
        }

        public string Decode
        {
            get
            {
                return _decode;
            }
            set
            {
                _decode = value;
            }
        }

        public string MinValue
        {
            get
            {
                return _minValue;
            }
            set
            {
                _minValue = value;
            }
        }

        public string MaxValue
        {
            get
            {
                return _maxValue;
            }
            set
            {
                _maxValue = value;
            }
        }

        public SymbolTable Group
        {
            get
            {
                return _group;
            }
            set
            {
                _group = value;
            }
        }
    }
}
